### ISSUE TITLE
workflow failing

### ISSUE THREAD

**Issue by userMeh** [rithikasilva/readme-lol-stats#5]
![image](https://github.com/rithikasilva/readme-lol-stats/assets/102216594/25b400e7-0855-4240-81c7-3342be277e64)

**Comment by rithikasilva** [comment]
Thanks for the issue creation! Looks like you might be using `rithikasilva/readme-lol-stats@v0.1` where it was using a deprecated endpoint. I forgot to explicitly update the usage example to use `@v0.1.1` instead of `v0.1`. I'll update the README shortly to make it a bit more obvious. As a heads up, note that GitHub has changed the way they render gifs, so your output will look a little wonky. I'll try to figure something out for this soon. You are welcome to make a PR in the meantime if you have a solution :).

**Comment by rithikasilva** [comment]
README updated. Please reopen if the issue persists. Again, keep in mind that the formatting is currently wonky (everything locally should appear correct should you use something like VSCode's Markdown Previewer). I will try to get a fix up soon for it.

EDIT: The issue of weird formatting was caused by having "Autoplay Animated Images" set to "Sync with System" under GitHub accessibility settings. We want it to be "Enabled". Fortunately no code changes are required.

**Comment by userMeh** [comment]
I actually already set the v0.1.1 heres the yml of that I ran:

```yaml
name: Run readme-lol-stats

on:    
    workflow_dispatch:

jobs:
    build:    
        runs-on: ubuntu-latest
        steps:
            # Checkout current repo to runner
          - name: Checkout current repo
            uses: actions/checkout@v4
            
            # Setup python
          - name: setup python
            uses: actions/setup-python@v5
            with:
                python-version: '3.9'
        
            # Upgrade pip
          - name: Upgrade Pip
            run: |
                python -m pip install --upgrade pip
            
            # Run readme-lol-stats-action
          - name: Use readme-lol-stats-action
            uses: rithikasilva/readme-lol-stats@v0.1.1
            with:
                source: ${{ github.event.repository.name }}
                api-key: ${{ secrets.API_KEY }}
            
            # Commit files to current repo
          - name: commit files
            run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add -A
                git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
            
            # Push changes to current repo
          - name: push changes
            uses: ad-m/github-push-action@v0.8.0
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: main
```
